# SPDX-FileCopyrightText: 2023 froggie <incoming@frogg.ie>
#
# SPDX-License-Identifier: OSL-3.0

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 25
    reviewers:
      - "5HT2"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    labels:
      - "triage:pending"
      - "backend:deps"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 25
    reviewers:
      - "5HT2"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    labels:
      - "triage:pending"
      - "backend:deps"

  - package-ecosystem: "npm"
    directory: "/ui"
    open-pull-requests-limit: 25
    reviewers:
      - "5HT2"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    labels:
      - "triage:pending"
      - "web:deps"
