# SPDX-FileCopyrightText: 2023 froggie <incoming@frogg.ie>
#
# SPDX-License-Identifier: OSL-3.0

version: "3.9"
services:
  app:
    container_name: tripreporter
    build: .
    restart: always
    env_file: [".env"]
    volumes:
      - "./config/:/tripreporter/config/"
    networks:
      - tripreporter-net
    ports:
      - "${DOCKER_SRV_HOST}:${SRV_PORT}:${SRV_PORT}"

  postgres:
    container_name: tripreporter-postgres
    image: postgres
    build: db/.
    restart: always
    env_file: [".env"]
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    expose:
      - "${DB_PORT}"
    networks:
      - tripreporter-net

  redis:
    container_name: tripreporter-redis
    image: "redis:alpine"
    restart: always
    env_file: [".env"]
    volumes:
      - "redis_data:/data"
      - "./config/redis.conf:/data/config/redis.conf"
    command: "/data/config/redis.conf"
    expose:
      - "${REDIS_PORT}"
    networks:
      - tripreporter-net

volumes:
  redis_data:

networks:
  tripreporter-net:
    driver: bridge
