name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        id: setup_repo

      - name: Setup Docker image
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        shell: bash
        working-directory: ${{ env.SRC_DIR }}
        run: |
          docker buildx bake \
          -f docker-compose.yml \
          --builder ${{ steps.buildx.outputs.name }} \
          --set *.cache-from="type=gha,scope=${{ runner.os }}-${{ github.workflow }}" \
          --set *.cache-to="type=gha,scope=${{ runner.os }}-${{ github.workflow }},mode=max"

#      - name: Build Docker image
#        uses: docker/build-push-action@v4
#        with:
#          push: false
#          context: .
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
