name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        id: setup_repo

      - name: Setup Docker image
        uses: docker/setup-buildx-action@v2
        id: setup_buildx

      - name: Build Docker image
        shell: bash
        working-directory: ${{ env.SRC_DIR }}
        run: |
          cp .env.example .env && \
          cp config/redis.conf.example config/redis.conf && \
          docker buildx bake \
          -f docker-compose.yml \
          --builder ${{ steps.setup_buildx.outputs.name }} \
          --set *.cache-from="type=gha,url=$ACTIONS_CACHE_URL,token=$ACTIONS_RUNTIME_TOKEN,scope=${{ runner.os }}-${{ github.workflow }}" \
          --set *.cache-to="type=gha,url=$ACTIONS_CACHE_URL,token=$ACTIONS_RUNTIME_TOKEN,scope=${{ runner.os }}-${{ github.workflow }},mode=max"
