name: make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: '1.19.x'
        id: setup_go

      - name: Cache Go
        with:
          tag_name: ${{ steps.setup_go.outputs.GOMODCACHE }}
        run: echo ${GOMODCACHE}

      - name: Build project
        run: make
