# SPDX-FileCopyrightText: 2023 froggie <incoming@frogg.ie>
#
# SPDX-License-Identifier: OSL-3.0

name: make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        id: setup_repo

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
        id: setup_node

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: '1.19.x'
        id: setup_go

      - name: Cache Go
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup_go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
        id: cache_go

      - name: Build project
        run: make
        id: run_make
